version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: flancer_db
    restart: always
    environment:
      MYSQL_DATABASE: flancer_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
